= TODO

* [x] Add the "help" flag callback to all commands and commandnodes that do not have
      the "disableHelp" flag set.

* [x] Render command aliases in the help text.

* [ ] Ensure command name/alias uniqueness only in build-tree and build-branch.
      It is pointless to check at the command-group level as you will just need
      to check at the tree/branch level again anyway to ensure the level itself
      is good.

* [x] The "Usage:" help line for subcommands should print the full command path
      to the command in question.  For example `docker compose up [OPTIONS] [SERVICES...]`

* [x] ExpectUnmapped(label string)
+
--
Example: `ExpectUnmapped("SERVICES...")`
--

* [ ] Document default groups.

* [x] Build default help printer and meta command group.
+
--
This flag should be appended, at build time, to either the default group (if
there are no custom flag groups) or its own meta flag group.
--
** [x] Command
** [x] Command Tree
** [x] Command Branch
** [x] Command Leaf

* [x] Ensure there are no spaces in the subcommand names

* [ ] Should a required argument with a default value be a warning?

* [ ] Show unshadowed commands from the parent command node under a heading like
      "Parent Flags" or "Inherited Flags" or "\{command} Flags" or something.
      Probably put it below the command specific flags as they are of less
      interest. +
      But wait... if they are of less interest than the subcommands they should
      appear after subcommands?  Are they of less interest than arguments?

* [ ] Indicate when a flag is required somehow in the help text.

* [ ] Indicate the difference between a leaf and a branch in the help docs
      somehow, maybe trail branches with an ellipsis or something?

* [ ] If an entire short flag block is unmatched, should it still be split into
      separate short flags?

* [x] "Argument 0 is required" should be one based.

* [ ] If another flag group declares the name "Flags" what should we do about
      the default flag group?

* [ ] If another flag group declares the name "Help Flags", what should we do
      about the auto help flags?

* [ ] If another command group declares the name "Commands", what should we do
      about the default command group?

* [ ] What happens if a boolean flag is given an empty argument?  And should it
      count that as true?